//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPFS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPFS_SPEND_SUPPLIERS
    {
        public SPFS_SPEND_SUPPLIERS()
        {
            this.SPFS_LINK_ERP = new HashSet<SPFS_LINK_ERP>();
            this.SPFS_STAGING_SUPPLIER_RATINGS = new HashSet<SPFS_STAGING_SUPPLIER_RATINGS>();
            this.SPFS_SUPPLIER_RATINGS = new HashSet<SPFS_SUPPLIER_RATINGS>();
        }
    
        public int Spend_supplier_ID { get; set; }
        public int SiteID { get; set; }
        public int SupplierID { get; set; }
        public decimal Total_Spend { get; set; }
        public int Reject_incident_count { get; set; }
        public int Reject_parts_count { get; set; }
        public Nullable<System.DateTime> Created_date { get; set; }
        public string Created_by { get; set; }
        public Nullable<System.DateTime> Modified_date { get; set; }
        public string Modified_by { get; set; }
    
        public virtual ICollection<SPFS_LINK_ERP> SPFS_LINK_ERP { get; set; }
        public virtual SPFS_SITES SPFS_SITES { get; set; }
        public virtual SPFS_SUPPLIERS SPFS_SUPPLIERS { get; set; }
        public virtual ICollection<SPFS_STAGING_SUPPLIER_RATINGS> SPFS_STAGING_SUPPLIER_RATINGS { get; set; }
        public virtual ICollection<SPFS_SUPPLIER_RATINGS> SPFS_SUPPLIER_RATINGS { get; set; }
    }
}
