//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPFS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPFS_STAGING_SUPPLIER_RATINGS
    {
        public int StagingID { get; set; }
        public System.DateTime Rating_period { get; set; }
        public int SiteID { get; set; }
        public int SupplierID { get; set; }
        public int Spend_supplierID { get; set; }
        public int Gdis_org_entity { get; set; }
        public int duns { get; set; }
        public int cid { get; set; }
        public int Erp_supplier_id { get; set; }
        public decimal Inbound_parts { get; set; }
        public decimal OTR { get; set; }
        public decimal OTD { get; set; }
        public decimal PFR { get; set; }
        public System.DateTime Initial_submission_date { get; set; }
        public Nullable<bool> Temp_Upload_ { get; set; }
        public int UserID { get; set; }
        public Nullable<System.DateTime> Created_date { get; set; }
        public string Created_by { get; set; }
        public Nullable<System.DateTime> Modified_date { get; set; }
        public string Modified_by { get; set; }
    
        public virtual SPFS_SITES SPFS_SITES { get; set; }
        public virtual SPFS_SPEND_SUPPLIERS SPFS_SPEND_SUPPLIERS { get; set; }
        public virtual SPFS_SUPPLIERS SPFS_SUPPLIERS { get; set; }
        public virtual SPFS_USERS SPFS_USERS { get; set; }
    }
}
